# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches:    
      - main
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            await exec.exec("sudo apt", ["install", "-y", "cloc"]);
            await exec.exec("cloc", ["--vcs=git", "--json", "--out=cloc-output.json"]);

            const clocResult = JSON.parse(fs.readFileSync("./cloc-output.json", "utf8"));

            const keys = Object.keys(clocResult).filter(x => x != "header");
            const series = keys.map(key => {
              const metric = clocResult[key];
              return {
                language: key,
                nFiles: metric.nFiles,
                blank: metric.blank,
                comment: metric.comment,
                code: metric.code 
              }
            });

            const summary = core.summary
            summary.addHeading("cloc")
            const headerRow = [
                  { data: "Language", header: true },
                  { data: "nFiles", header: true },
                  { data: "blank", header: true },
                  { data: "comment", header: true },
                  { data: "code", header: true },
                ];
            const otherRows = series.map(x => [x.language, x.nFiles.toString(), x.blank, x.comment, x.code]);
            const allRows = [headerRow, ...otherRows];
            summary.addTable(allRows);
            summary.write();
